#include "tinytest.h"

/* GENERATED by tools/gen_test_main.py -- do not edit by hand. */

int tt_checks = 0, tt_fails = 0;
const char *tt_current = "";

int tt_report(void) {
  printf("\n%d checks, %d failures\n", tt_checks, tt_fails);
  return tt_fails ? 1 : 0;
}

void test_locked_pointer_is_writable_and_stable(void);
void test_mem_zero_clears_the_block(void);
void test_blocks_do_not_overlap(void);
void test_lock_of_stale_handle_returns_null(void);
void test_alloc_fails_cleanly_when_heap_is_full(void);
void test_compaction_closes_a_gap_and_preserves_contents(void);
void test_compaction_does_not_move_a_locked_block(void);
void test_alloc_compacts_automatically_when_it_would_otherwise_fail(void);
void test_compaction_is_a_noop_when_there_are_no_gaps(void);
void test_fixed_blocks_sit_above_movable_blocks(void);
void test_fixed_block_never_moves_across_a_compaction(void);
void test_freed_fixed_blocks_are_coalesced_and_reused(void);
void test_fixed_and_movable_arenas_cannot_collide(void);
void test_alloc_returns_distinct_nonzero_handles(void);
void test_handle_zero_is_always_invalid(void);
void test_freed_handle_is_detected_as_stale(void);
void test_generation_never_becomes_zero(void);
void test_handle_table_exhaustion_returns_zero(void);
void test_oversized_allocation_is_refused(void);

int main(void) {
  printf("-- mem alloc --\n");
  RUN(test_locked_pointer_is_writable_and_stable);
  RUN(test_mem_zero_clears_the_block);
  RUN(test_blocks_do_not_overlap);
  RUN(test_lock_of_stale_handle_returns_null);
  RUN(test_alloc_fails_cleanly_when_heap_is_full);
  printf("-- mem compact --\n");
  RUN(test_compaction_closes_a_gap_and_preserves_contents);
  RUN(test_compaction_does_not_move_a_locked_block);
  RUN(test_alloc_compacts_automatically_when_it_would_otherwise_fail);
  RUN(test_compaction_is_a_noop_when_there_are_no_gaps);
  printf("-- mem fixed --\n");
  RUN(test_fixed_blocks_sit_above_movable_blocks);
  RUN(test_fixed_block_never_moves_across_a_compaction);
  RUN(test_freed_fixed_blocks_are_coalesced_and_reused);
  RUN(test_fixed_and_movable_arenas_cannot_collide);
  printf("-- mem handles --\n");
  RUN(test_alloc_returns_distinct_nonzero_handles);
  RUN(test_handle_zero_is_always_invalid);
  RUN(test_freed_handle_is_detected_as_stale);
  RUN(test_generation_never_becomes_zero);
  RUN(test_handle_table_exhaustion_returns_zero);
  RUN(test_oversized_allocation_is_refused);
  return tt_report();
}
