#!/usr/bin/env python3
"""Generate test/test_main.c from every `void test_*(void)` in test/test_*.c.

Hand-maintaining a test registry means a test can be written, compiled, and
then silently never run -- the worst failure mode a suite can have. Generating
it makes that impossible.
"""
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
NL = "\\n"  # a literal backslash-n, to be emitted inside C string literals

pattern = re.compile(r"^void\s+(test_[A-Za-z0-9_]+)\s*\(\s*void\s*\)", re.M)

groups = []
for path in sorted((ROOT / "test").glob("test_*.c")):
    if path.name == "test_main.c":
        continue
    names = pattern.findall(path.read_text())
    if names:
        title = path.stem[len("test_"):].replace("_", " ")
        groups.append((title, names))

seen = {}
for title, names in groups:
    for n in names:
        if n in seen:
            raise SystemExit(
                "duplicate test name %s in %s and %s -- test names are global "
                "C symbols and must be unique" % (n, seen[n], title))
        seen[n] = title

out = [
    '#include "tinytest.h"',
    "",
    "/* GENERATED by tools/gen_test_main.py -- do not edit by hand. */",
    "",
    "int tt_checks = 0, tt_fails = 0;",
    'const char *tt_current = "";',
    "",
    "int tt_report(void) {",
    '  printf("%s%%d checks, %%d failures%s", tt_checks, tt_fails);' % (NL, NL),
    "  return tt_fails ? 1 : 0;",
    "}",
    "",
]

for _, names in groups:
    for name in names:
        out.append("void %s(void);" % name)

out += ["", "int main(void) {"]
for title, names in groups:
    out.append('  printf("-- %s --%s");' % (title, NL))
    for name in names:
        out.append("  RUN(%s);" % name)
out += ["  return tt_report();", "}", ""]

(ROOT / "test" / "test_main.c").write_text("\n".join(out))
print("generated %d tests from %d files"
      % (sum(len(n) for _, n in groups), len(groups)))
