#!/usr/bin/env python3
"""Rasterise a 6x8 console font into kernel/console/font6x8.h.

The console is 240x135 at 6x8 pixels per cell, which is exactly 40x16
characters. Generating the font from a real monospace face beats hand-writing
95 glyphs: it is reproducible, and the script is the source of truth.

Each glyph is 6 bytes, one per column, bit 0 = top row. Column-major suits the
display driver, which walks a character cell left to right.

Usage: python tools/gen_font.py
"""
import pathlib
from PIL import Image, ImageDraw, ImageFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "kernel" / "console" / "font6x8.h"

CELL_W, CELL_H = 6, 8
FIRST, LAST = 32, 126           # printable ASCII

CANDIDATES = [
    ("C:/Windows/Fonts/consola.ttf", 10),
    ("C:/Windows/Fonts/cour.ttf", 11),
]


def load_font():
    for path, size in CANDIDATES:
        if pathlib.Path(path).exists():
            return ImageFont.truetype(path, size), path, size
    raise SystemExit("no usable monospace TTF found")


def render(font, ch):
    """Return CELL_W columns of CELL_H bits for one character."""
    img = Image.new("L", (CELL_W, CELL_H), 0)
    draw = ImageDraw.Draw(img)
    # Nudge the glyph up into the cell: TTF metrics leave leading above the
    # cap height, which would otherwise push descenders out of the bottom.
    # 10px Consolas at dy=-2 was chosen by eye over 9/11px and Courier -- it
    # is the only combination where A keeps its crossbar and g keeps its tail.
    draw.text((0, -2), ch, fill=255, font=font)
    cols = []
    for x in range(CELL_W):
        bits = 0
        for y in range(CELL_H):
            if img.getpixel((x, y)) >= 128:
                bits |= 1 << y
        cols.append(bits)
    return cols


def main():
    font, path, size = load_font()
    glyphs = [render(font, chr(c)) for c in range(FIRST, LAST + 1)]

    lines = [
        "/* GENERATED by tools/gen_font.py -- do not edit by hand.",
        " *",
        " * 6x8 console font, ASCII %d..%d." % (FIRST, LAST),
        " * Six bytes per glyph, one per column, bit 0 = top row.",
        " * Rasterised from %s at %dpx." % (path, size),
        " */",
        "#ifndef CARDOS_FONT6X8_H",
        "#define CARDOS_FONT6X8_H",
        "",
        "#include <stdint.h>",
        "",
        "#define FONT_W %d" % CELL_W,
        "#define FONT_H %d" % CELL_H,
        "#define FONT_FIRST %d" % FIRST,
        "#define FONT_LAST %d" % LAST,
        "",
        "static const uint8_t font6x8[%d][%d] = {" % (len(glyphs), CELL_W),
    ]
    for code, cols in zip(range(FIRST, LAST + 1), glyphs):
        body = ", ".join("0x%02X" % c for c in cols)
        ch = chr(code)
        label = "space" if ch == " " else ("backslash" if ch == "\\" else ch)
        lines.append("  { %s },  /* %s */" % (body, label))
    lines += ["};", "", "#endif /* CARDOS_FONT6X8_H */", ""]

    OUT.write_text("\n".join(lines))
    print("wrote %s: %d glyphs from %s" % (OUT, len(glyphs), path))


if __name__ == "__main__":
    main()
