#!/usr/bin/env python3
"""Generate kernel/ui/icons_builtin.h -- 16x16 icons for the built-in apps.

The launcher draws every icon at 4x, so these are read as 64x64 pixel art and
every set bit is a visible 4x4 block. They are written here as pictures for the
same reason the font is: --show renders the generated table back out, so a
wrong row is visible rather than hiding in hex.

Format matches what a .capp supplies -- 16 rows of 2 bytes, bit 7 leftmost --
so the launcher has one drawing path for built-ins and loaded apps alike.
"""

import sys

ART = {
    # A folder, with the tab on the left the way every file manager draws it.
    "Files": [
        "................",
        "................",
        "..######........",
        ".#......#.......",
        ".#.......######.",
        ".#............#.",
        ".#............#.",
        ".#............#.",
        ".#............#.",
        ".#............#.",
        ".#............#.",
        ".#............#.",
        ".#............#.",
        "..############..",
        "................",
        "................",
    ],
    # A DIP package: body, legs down both sides, and the notch that says which
    # end is pin one.
    "Memory": [
        "................",
        "................",
        "..#..........#..",
        ".####......####.",
        ".#..########..#.",
        ".#..#......#..#.",
        "....#..##..#....",
        ".####..##..####.",
        ".####..##..####.",
        "....#..##..#....",
        ".#..#......#..#.",
        ".#..########..#.",
        ".####......####.",
        "..#..........#..",
        "................",
        "................",
    ],
    # A gear. Four teeth and a hollow centre reads as one at this size; six
    # teeth turns into a blur.
    "Settings": [
        "................",
        "......####......",
        "......####......",
        "...##########...",
        "..############..",
        "..####....####..",
        "###.##....##.###",
        "###.#......#.###",
        "###.#......#.###",
        "###.##....##.###",
        "..####....####..",
        "..############..",
        "...##########...",
        "......####......",
        "......####......",
        "................",
    ],
    # A lowercase i in a ring.
    "About": [
        "................",
        "....########....",
        "..############..",
        ".####......####.",
        "###...####...###",
        "###...####...###",
        "###..........###",
        "###...####...###",
        "###.....##...###",
        "###.....##...###",
        "###.....##...###",
        ".####..####.###.",
        "..############..",
        "....########....",
        "................",
        "................",
    ],
    # A board with a chip and a header: what a firmware image is, as opposed to
    # an app.
    "firmware": [
        "................",
        ".##############.",
        ".#............#.",
        ".#.#.#.#.#.#..#.",
        ".#............#.",
        ".#..########..#.",
        ".#..#......#..#.",
        ".#..#......#..#.",
        ".#..#......#..#.",
        ".#..########..#.",
        ".#............#.",
        ".#.##.##.##...#.",
        ".#............#.",
        ".##############.",
        "................",
        "................",
    ],
    # The fallback, for an app with no icon of its own: a blank page with a
    # folded corner.
    "generic": [
        "................",
        "...#########....",
        "...#.......##...",
        "...#.......#.#..",
        "...#.......#..#.",
        "...#.......#####",
        "...#...........#",
        "...#...........#",
        "...#...........#",
        "...#...........#",
        "...#...........#",
        "...#...........#",
        "...#############",
        "................",
        "................",
        "................",
    ],
}

ORDER = ["Files", "Memory", "Settings", "About", "firmware", "generic"]


def pack(art):
    assert len(art) == 16, len(art)
    out = []
    for row in art:
        assert len(row) == 16, row
        hi = lo = 0
        for c in range(8):
            if row[c] == "#":
                hi |= 1 << (7 - c)
            if row[c + 8] == "#":
                lo |= 1 << (7 - c)
        out += [hi, lo]
    return out


def render(b):
    for r in range(16):
        hi, lo = b[r * 2], b[r * 2 + 1]
        line = "".join("#" if (hi >> (7 - c)) & 1 else "." for c in range(8))
        line += "".join("#" if (lo >> (7 - c)) & 1 else "." for c in range(8))
        print("  " + line)


def main():
    if "--show" in sys.argv:
        for name in ORDER:
            print(name + ":")
            render(pack(ART[name]))
        return

    lines = [
        "/* 16x16 icons for the built-in apps, generated by tools/make_icons.py.",
        " * Do not edit -- edit the pictures in the generator.",
        " *",
        " * Same format a .capp supplies: 16 rows of two bytes, bit 7 leftmost,",
        " * so the launcher has one drawing path for built-ins and loaded apps",
        " * alike. The launcher draws them at 4x, which is why they are designed",
        " * as pixel art rather than as shrunken illustrations.",
        " */",
        "#ifndef CARDOS_ICONS_BUILTIN_H",
        "#define CARDOS_ICONS_BUILTIN_H",
        "",
        "#include <stdint.h>",
        "",
    ]
    for name in ORDER:
        b = pack(ART[name])
        # ICON_FIRMWARE is taken by the IconKind enumerator, so the table's
        # entry gets a trailing underscore rather than a different scheme.
        sym = "ICON_" + name.upper() + ("_" if name == "firmware" else "")
        lines.append("static const uint8_t %s[32] = {" % sym)
        for i in range(0, 32, 8):
            lines.append("  " + " ".join("0x%02X," % v for v in b[i:i + 8]))
        lines.append("};")
        lines.append("")
    lines += ["#endif /* CARDOS_ICONS_BUILTIN_H */"]

    with open("kernel/ui/icons_builtin.h", "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote kernel/ui/icons_builtin.h (%d icons)" % len(ORDER))


if __name__ == "__main__":
    main()
