idf_component_register(
  SRCS
    "main.c"
    "shellcmd.c"
    "../kernel/drv/display.c"
    "../kernel/drv/keyboard.c"
    "../kernel/drv/btmouse.c"
    "../kernel/drv/vendor/esp_hid_gap.c"
    "../kernel/console/console.c"
    "../kernel/task/sched.c"
    "../kernel/fs/path.c"
    "../kernel/input/mouse.c"
    "../kernel/ui/rect.c"
    "../kernel/ui/wm.c"
    "../kernel/ui/draw.c"
    "../kernel/ui/desktop.c"
    "../kernel/ui/apps.c"
    "../kernel/fs/fs_fat.c"
    "../kernel/mem/mem.c"
    "../kernel/swap/swap.c"
    "../kernel/app/appimage.c"
    "../kernel/app/launcher.c"
  INCLUDE_DIRS
    "."
    ".."      # CardOS headers are included as "kernel/..."
  REQUIRES
    driver
    esp_lcd
    fatfs
    sdmmc
    app_update
    esp_timer
    esp_driver_usb_serial_jtag
    bt
    esp_hid
    nvs_flash
)
